import { StyleSheet } from "react-native";
import { client, colors } from "../../theme/colors";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: client.primary,
        backgroundColor: colors.background,
    },
    backButton: {
        paddingHorizontal: 8,
        paddingVertical: 8,
    },
    backButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: client.primary,
    },
    headerTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.text.primary,
    },
    progressContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: colors.background,
    },
    progressBar: {
        height: 4,
        backgroundColor: colors.border,
        borderRadius: 2,
        overflow: 'hidden',
        marginBottom: 8,
    },
    progressFill: {
        height: '100%',
        backgroundColor: client.primary,
    },
    progressText: {
        fontSize: 12,
        color: colors.text.secondary,
        textAlign: 'center',
    },
    stepIndicator: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        marginBottom: 16,
        backgroundColor: colors.background,
        paddingVertical: 12,
    },
    stepDot: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.border,
    },
    stepDotActive: {
        backgroundColor: client.light,
        borderColor: client.primary,
    },
    stepDotCurrent: {
        backgroundColor: client.primary,
        borderColor: client.primary,
    },
    stepNumber: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.text.secondary,
    },
    checkmarkSmall: {
        fontSize: 18,
        color: '#FFFFFF',
        fontWeight: '700',
    },
    content: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingVertical: 20,
    },
    stepContent: {
        marginBottom: 20,
    },
    stepTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.text.primary,
        marginBottom: 6,
    },
    stepDescription: {
        fontSize: 13,
        color: colors.text.secondary,
        marginBottom: 20,
    },
    categoryCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 14,
        borderWidth: 2,
        borderColor: colors.border,
    },
    categoryCardSelected: {
        backgroundColor: client.light,
        borderColor: client.primary,
    },
    categoryIcon: {
        fontSize: 32,
        marginRight: 12,
    },
    categoryInfo: {
        flex: 1,
    },
    categoryLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text.primary,
        marginBottom: 4,
    },
    categoryDescription: {
        fontSize: 12,
        color: colors.text.tertiary,
    },
    checkmark: {
        fontSize: 20,
        color: client.primary,
        fontWeight: '700',
    },
    formGroup: {
        marginBottom: 20,
    },
    label: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.text.primary,
        marginBottom: 8,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        paddingHorizontal: 12,
    },
    inputIcon: {
        fontSize: 18,
        marginRight: 8,
    },
    currencySymbol: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.text.secondary,
        marginRight: 4,
    },
    input: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 0,
        fontSize: 14,
        color: colors.text.primary,
    },
    priceInput: {
        textAlign: 'right',
    },
    textArea: {
        paddingVertical: 10,
        textAlignVertical: 'top',
    },
    optionCard: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 10,
        paddingVertical: 12,
        paddingHorizontal: 14,
        borderWidth: 1,
        borderColor: colors.border,
    },
    optionCardSelected: {
        backgroundColor: client.light,
        borderColor: client.primary,
    },
    optionLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.text.primary,
    },
    summaryCard: {
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    summarySection: {
        marginBottom: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    summaryLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.text.secondary,
        marginBottom: 6,
        textTransform: 'uppercase',
    },
    summaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    summaryIcon: {
        fontSize: 24,
    },
    summaryValue: {
        fontSize: 14,
        fontWeight: '500',
        color: colors.text.primary,
        lineHeight: 20,
    },
    priceText: {
        fontSize: 18,
        fontWeight: '700',
        color: client.primary,
    },
    infoBox: {
        flexDirection: 'row',
        backgroundColor: colors.borderLight,
        borderRadius: 10,
        padding: 12,
        gap: 10,
        marginTop: 20,
    },
    infoIcon: {
        fontSize: 20,
    },
    infoText: {
        flex: 1,
        fontSize: 12,
        color: colors.text.secondary,
        lineHeight: 18,
    },
    buttonContainer: {
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 16,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        backgroundColor: colors.background,
    },
    backNavigationButton: {
        flex: 1,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
    },
    backNavigationButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text.primary,
    },
    nextButton: {
        flex: 1,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        backgroundColor: client.primary,
    },
    nextButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    submitButton: {
        flex: 1,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        backgroundColor: client.dark,
    },
    submitButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },
});
