// AUTO-GENERATED (for frontend) - Types consolidated from FixIt backend
// Generated by developer assistant. Review before use.

// Generic API wrapper used by microservices: { success: boolean, data?: T, error?: string, statusCode?: number }
export type ApiResponse<T> = {
  success: boolean;
  data?: T;
  error?: string;
  statusCode?: number;
  message?: string;
};

// Enums (copied from prisma/backend DTOs)
export enum RolUsuario {
  ADMIN = 'ADMIN',
  TECNICO = 'TECNICO',
  CLIENTE = 'CLIENTE'
}

export enum EstadoSolicitud {
  PENDIENTE = 'PENDIENTE',
  ACEPTADA = 'ACEPTADA',
  CANCELADA = 'CANCELADA',
  COMPLETADA = 'COMPLETADA'
}

export enum EstadoAceptacion {
  PROPUESTO = 'PROPUESTO',
  ACEPTADO = 'ACEPTADO',
  RECHAZADO = 'RECHAZADO'
}

export enum MetodoPago {
  EFECTIVO = 'EFECTIVO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  TARJETA = 'TARJETA',
  OTRO = 'OTRO'
}

// ---------- AUTH / USERS ----------

export interface Usuario {
  idUser: number;
  cedula: string;
  nombres: string;
  apellidos: string;
  email: string;
  telefono?: string;
  direccion?: string;
  fechaNacimiento?: string; // ISO date
  rol: RolUsuario;
  emailVerificado: boolean;
  activo: boolean;
  isActive: boolean;
  deletedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export type UsuarioSinPassword = Omit<Usuario, 'password' | 'passwordHash'>;

export type LoginRequest = { email: string; password: string } | { cedula: string; password: string };

export interface AuthResponse {
  access_token: string;
  refresh_token: string;
  user: {
    idUser: number;
    cedula: string;
    nombres: string;
    apellidos: string;
    email: string;
    rol: RolUsuario;
  };
}

// Example responses
export const ExampleAuthResponse: ApiResponse<AuthResponse> = {
  success: true,
  data: {
    access_token: 'eyJhbGciOi...',
    refresh_token: 'eyJhbGc...',
    user: {
      idUser: 123,
      cedula: '0102030405',
      nombres: 'Juan',
      apellidos: 'Perez',
      email: 'juan@example.com',
      rol: RolUsuario.CLIENTE,
    }
  }
};

// ---------- REQUEST / SOLICITUDES ----------

export interface CreateSolicitudDto {
  idTipoServicio: number;
  codigoParroquia: string;
  tituloProblema: string;
  descripcionProblema: string;
  costoEstimado?: number | string; // Prisma Decimal often serialized as string
  costoPromocion?: number | string;
  promocion?: boolean;
  fechaProgramada?: string; // ISO date
  duracionEstimadaMin?: number;
}

export interface Solicitud {
  idSolicitud: number;
  idUser: number;
  idTipoServicio: number;
  codigoParroquia: string;
  tituloProblema: string;
  descripcionProblema: string;
  costoEstimado?: number | string;
  costoPromocion?: number | string;
  promocion: boolean;
  estadoSolicitud: EstadoSolicitud;
  fechaProgramada?: string;
  fechaPublicacion: string;
  fechaInicio?: string;
  fechaFinalizacion?: string;
  duracionEstimadaMin?: number;
  isActive: boolean;
  deletedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PaginatedSolicitudes {
  solicitudes: Solicitud[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

export const ExampleCreateSolicitud: CreateSolicitudDto = {
  idTipoServicio: 1,
  codigoParroquia: '090101',
  tituloProblema: 'Fuga de agua en cocina',
  descripcionProblema: 'Hay una fuga persistente bajo el fregadero que moja el mueble y el piso.',
  costoEstimado: 25.5,
  promocion: false
};

export const ExampleSolicitudResponse: ApiResponse<Solicitud> = {
  success: true,
  data: {
    idSolicitud: 10,
    idUser: 123,
    idTipoServicio: 2,
    codigoParroquia: '090101',
    tituloProblema: 'Fuga de agua en cocina',
    descripcionProblema: 'Hay una fuga persistente bajo el fregadero que moja el mueble y el piso.',
    costoEstimado: '25.50',
    costoPromocion: undefined,
    promocion: false,
    estadoSolicitud: EstadoSolicitud.PENDIENTE,
    fechaProgramada: undefined,
    fechaPublicacion: new Date().toISOString(),
    fechaInicio: undefined,
    fechaFinalizacion: undefined,
    duracionEstimadaMin: 60,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
};

// ---------- TECHNICIAN / TECNICOS ----------

export interface Tecnico {
  idTecnico: number;
  idUser: number;
  totalCalificaciones: number;
  promedioCalificaciones?: number;
  isActive: boolean;
  deletedAt?: string;
  createdAt: string;
  updatedAt: string;
  createdBy?: number;
  updatedBy?: number;
}

export interface TecnicoWithDetails extends Tecnico {
  usuario?: {
    nombres: string;
    apellidos: string;
    email: string;
    telefono?: string;
  };
  certificaciones?: any[];
  parroquias?: any[];
  servicios?: any[];
  calificaciones?: any[];
  _count?: { solicitudesTecnico: number; calificaciones: number };
}

export const ExampleTecnicoListResponse: ApiResponse<TecnicoWithDetails[]> = {
  success: true,
  data: [
    {
      idTecnico: 5,
      idUser: 200,
      totalCalificaciones: 12,
      promedioCalificaciones: 4.5,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ]
};

// ---------- SolicitudTecnico (propuesta de técnico) ----------
export interface SolicitudTecnico {
  idSolTec: number;
  idSolicitud: number;
  idTecnico: number;
  costoAcordado?: number | string;
  estadoAcuerdo: EstadoAceptacion | string;
  fechaPropuesta: string;
  fechaConfirmada?: string;
  notas?: string;
  createdAt: string;
  updatedAt: string;
}

export const ExampleSolicitudTecnicoResponse: ApiResponse<SolicitudTecnico> = {
  success: true,
  data: {
    idSolTec: 7,
    idSolicitud: 10,
    idTecnico: 5,
    costoAcordado: '30.00',
    estadoAcuerdo: EstadoAceptacion.PROPUESTO,
    fechaPropuesta: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
};

// ---------- NOTES / GUIDANCE ----------
/*
- Numeric decimals: Prisma `Decimal` fields are often serialized as strings when sent over JSON.
  The frontend should accept both `string` and `number` for monetary values (see types above).

- Endpoint mapping differences to be aware of:
  - Backend microservices are message-based. API Gateway exposes HTTP endpoints and forwards to microservices.
  - The repository exposes `POST /usuarios` (API Gateway) for creating users (register). There is
    no `POST /auth/register` route; document mapping accordingly.

- Response wrapper: most microservices return an envelope: `{ success: boolean, data: any, error?: string }`.
  Frontend should always check `success` before using `data`.

- IDs naming: backend uses `idUser`, `idSolicitud`, `idTecnico`, `idTipoServicio`. Watch for frontend
  using `id` or `userId`—be consistent with backend names to avoid bugs.

*/
